parent=keycloak
import=common/keycloak

# CSS dosyamızı bağlıyoruz
styles=css/styles.css

# Sayfa başlığı
title=MealAI - Giriş Yap

locales=tr,en

# Eğer login ekranına kendi JS dosyalarını eklemek istersen:
# scripts=js/script.js
