-- V16: Add profile image URL to users and image URL/nutrition/rating fields to recipes
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(512);

ALTER TABLE recipes ADD COLUMN IF NOT EXISTS image_url VARCHAR(512);
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_calories DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_protein DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_carbs DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_fat DOUBLE PRECISION;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS average_rating DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS rating_count INTEGER DEFAULT 0;
